export enum Member {
  moratorium = 'moratorium08',
  CoiL = 'CoiL',
  iLiss = 'iLiss.',
  OkXgen = 'OkXgen',
  naan = 'ナン',
  Mister = 'Mister',
  ura = 'うら',
  azaika = 'azaika',
  fiord = 'fiord',
  kuromunori = 'kuromunori',
  yamayu = 'yamayu',
  JP3BGY = 'JP3BGY',
  dai = 'dai',
  hideo54 = 'hideo54',
  hyoshiok = 'hyoshiok',
  bitmath = 'bitmath',
  torisasami = 'torisasami',
  sena = 'sena',
  kombu = '昆布',
  Naomiat = 'NaomiatLibrary',
  taiyoslime = 'taiyoslime',
  Hoget = 'Hoget157',
  satos = 'satos',
  KazukiOta = 'KazukiOta'
}